source = $HOME/.config/hypr/monitor.conf
source = $HOME/.config/hypr/startup.conf
source = $HOME/.config/hypr/env.conf
source = $HOME/.config/hypr/keybings.conf

monitor = eDP-1,disable

input {
    kb_layout = us
    kb_variant = colemak
    kb_options = ctrl:nocaps
		repeat_delay = 200
    repeat_rate = 30
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

general {
    border_size = 2
    gaps_in = 5
    gaps_out = 20
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = master
}

decoration {
    rounding = 10
    col.shadow = rgba(1a1a1aee)
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

misc {
		disable_hyprland_logo = true
}

master {
    new_is_master = true
		new_on_top = true
		orientation = left
		mfact = 0.5
}
