exec-once = $HOME/.config/system-scripts/hyprland/wallpaper/wp-change.sh
exec-once = waybar
exec-once = fcitx5
exec-once = dunst
exec-once = nm-applet
exec-once = pasystray
exec-once = blueberry-tray
exec-once = udiskie --no-automount --no-notify --tray

# cursor-theme
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
