exec-once = $HOME/.config/system-scripts/hyprland/wallpaper/wp-change.sh
exec-once = waybar
exec-once = fcitx5
exec-once = dunst
exec-once = nm-applet
exec-once = pasystray
exec-once = blueberry
exec-once = udiskie --no-automount --no-notify --tray
