[env]
  TERM = "xterm-256color"

[window]
	dimensions.columns = 120
	dimensions.lines = 50
	padding.x = 15
	padding.y = 10
	opacity = 0.9
	title = "Alacritty"
	dynamic_title = true
	class.instance = "Alacritty"
	class.general = "Alacritty"
	decorations_theme_variant = "Dark"

[scrolling]
	history = 10000
	multiplier = 3

[font]
	normal.family = "Sauce Code Pro Nerd Font"
	normal.style = "Regular"

	bold.family = "Sauce Code Pro Nerd Font"
	bold.style = "Bold"

	italic.family = "Sauce Code Pro Nerd Font"
	italic.style = "Italic"

	bold_italic.family = "Sauce Code Pro Nerd Font"
	bold_italic.style = "Bold Italic"

	size = 15

	offset.x = 1
	offset.y = 1

[colors]
	draw_bold_text_with_bright_colors = true

	# primary
  primary.background = '0x282828'
  primary.foreground = '0xd4be98'

	# normal
  normal.black =   '0x3c3836'
  normal.red =     '0xea6962'
  normal.green =   '0xa9b665'
  normal.yellow =  '0xd8a657'
  normal.blue =    '0x7daea3'
  normal.magenta = '0xd3869b'
  normal.cyan =    '0x89b482'
  normal.white =   '0xd4be98'

	# bright
  bright.black =   '0x3c3836'
  bright.red =     '0xea6962'
  bright.green =   '0xa9b665'
  bright.yellow =  '0xd8a657'
  bright.blue =    '0x7daea3'
  bright.magenta = '0xd3869b'
  bright.cyan =    '0x89b482'
  bright.white =   '0xd4be98'

	indexed_colors = []

[cursor]
	style.shape = "Block"
	style.blinking = "On"
	blink_interval = 750
	blink_timeout = 5
	unfocused_hollow = false

[mouse]
	hide_when_typing = true

[keyboard]
	
	bindings = [
	{key = "V",        mods = "Control|Shift",        action = "Paste"},
	{key = "C",        mods = "Control|Shift",        action = "Copy"},
	]
